[package]
name = "folio-pdf"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
folio-document = { path = "../document" }
thiserror.workspace = true
folio-platform = { path = "../platform" }
lopdf = { version = "=0.45.0", default-features = false }

[dev-dependencies]
serde_json.workspace = true
