[package]
name = "folio"
version.workspace = true
edition.workspace = true
license.workspace = true
build = "build.rs"

[dependencies]
gpui.workspace = true
folio-ui = { path = "../../crates/ui" }
folio-app = { path = "../../crates/app" }
anyhow.workspace = true
folio-platform = { path = "../../crates/platform" }
folio-storage = { path = "../../crates/storage" }
